##
## Makefile to create jar file
##

it :
	@ echo ""
	@ echo "Targets are clean and jar"
	@ echo ""

jar : GPAcalculator.jar

GPAcalculator.jar : ../GPAcalculator.jar
	cp ../GPAcalculator.jar .

clean : 
	- rm -f *.class

